name       : vivaldi-stable
version    : 1.12.955.36
release    : 32
source     :
    - https://downloads.vivaldi.com/stable/vivaldi-stable_1.12.955.36-1_amd64.deb : 12775223bfd916d8792dfbfa4d5cd5985def263ab6eb9e1ce5de6fec17d9063a
license    : Distributable
component  : network.web.browser
summary    : Vivaldi Web Browser
strip      : no
extract    : no
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
description: |
    An advanced browser made with the power user in mind.
setup      : |
    ar xf $sources/vivaldi-stable_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/{applications,doc,menu} $installdir/usr/share/

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    mv $installdir/usr/share/vivaldi $installdir/usr/share/vivaldi-stable

    # Restore bin link
    ln -sv /usr/share/vivaldi-stable/vivaldi $installdir/usr/bin/vivaldi-stable

    for icon_size in 16 22 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi.png
    done
