name       : vivaldi-stable
version    : 1.5.658.44
release    : 14
source     :
    - https://downloads.vivaldi.com/stable/vivaldi-stable_1.5.658.44-1_amd64.deb : d43cda11f6d9dffbdf3a0f7d29ba42a693f01db2aba4092904f51d88f84deb0b
license    : Distributable
component  : network.web.browser
summary    : Vivaldi Web Browser
strip      : no
extract    : no
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
description: |
    An advanced browser made with the power user in mind.
setup      : |
    ar xf $sources/vivaldi-stable_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/{applications,doc,menu} $installdir/usr/share/

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    mv $installdir/usr/share/vivaldi $installdir/usr/share/vivaldi-stable

    # Restore bin link
    ln -sv /usr/share/vivaldi-stable/vivaldi $installdir/usr/bin/vivaldi-stable

    for icon_size in 16 22 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi.png
    done
